### ISSUE TITLE
.css() getter doesn't seem to work on detached DOM nodes

### ISSUE THREAD

**Issue by limonte** [fabiospampinato/cash#336]
### Current behavior

```js
const cashElement = $('<div></div>')
cashElement.css({ top: 10 })
console.log(cashElement.css('top')) // empty string
```

### Expected behavior

`cashElement.css('top')` should return `10px`

### Live demo

https://jsfiddle.net/94wvmnp2/

**Comment by fabiospampinato** [comment]
I just "fixed" this for the sake of jQuery alignment, but I haven't made the release yet though as Travis is having [troubles](https://travis-ci.org/github/fabiospampinato/cash/builds/675359016) starting up the browsers, could you take a look at that?

I'm not sure this was actually a bug though, that node doesn't have `top: 10px` applied to it because it's disconnected from the DOM, that's just how browsers work. jQuery in that scenario is defaulting to the value we set earlier, but that's kind of meaningless as it's possible that once that node gets connected to the DOM it won't actually have `top: 10px` applied to it as that might get overridden by some stylesheet, so the return value of `$.fn.css` when dealing with disconnected nodes is kind of meaningless really, this "fix" may actually hide some potential bugs in your app, these sorts of manipulations of disconnected nodes should be avoided.

**Comment by limonte** [comment]
> I just "fixed" this for the sake of jQuery alignment, but I haven't made the release yet though as Travis is having [troubles](https://travis-ci.com/github/fabiospampinato/cash/builds/160403497) starting up the browsers, could you take a look at that?

Hm, looks like the issue is on the SauceLabs side, did you try to re-trigger the same build?

> I'm not sure this was actually a bug though, that node doesn't have `top: 10px` applied to it because it's disconnected from the DOM, that's just how browsers work. jQuery in that scenario is defaulting to the value we set earlier, but that's kind of meaningless as it's possible that once that node gets connected to the DOM it won't actually have `top: 10px` applied to it as that might get overridden by some stylesheet, so the return value of `$.fn.css` when dealing with disconnected nodes is kind of meaningless really, this "fix" may actually hide some potential bugs in your app, these sorts of manipulations of disconnected nodes should be avoided.

Roger, thanks!

**Comment by fabiospampinato** [comment]
> Hm, looks like the issue is on the SauceLabs side, did you try to re-trigger the same build?

Yeah. I'll try again tomorrow, hopefully they'll fix it by then.
