### ISSUE TITLE
Bootstrap compability

### ISSUE THREAD

**Issue by sookoll** [fabiospampinato/cash#343]
As I read from closed issue, cash-dom should work with Bootstrap. However, it doesn't in my setup (es6 modules):
webpack
babel
jquery
bootsrap

I try to replace jquery with cash-dom. First issue was that all Bootstrap modules try to import jquery namely. I got it fixed by creating webpack alias:

```
resolve: {
    alias: {
      jquery: 'cash-dom',
...
```
But then I ran into another issue. Bootstrap uses $.fn.jquery.split which is not available in cach-dom. There is probably more issues to come. Any workaround for this problem? I can't create $.fn.xx plugin, as this error happens during module load.

**Comment by fabiospampinato** [comment]
> As I read from closed issue, cash-dom should work with Bootstrap

Which issue? I haven't checked this specifically, but I think getting Cash to work with Bootstrap should be relatively easy, unless Bootstrap needs some complicated function Cash doesn't implement, which I don't think it's the case.

> But then I ran into another issue. Bootstrap uses $.fn.jquery.split which is not available in cach-dom. There is probably more issues to come. Any workaround for this problem? I can't create $.fn.xx plugin, as this error happens during module load.

`$.fn.jquery` is a string containing the version of jQuery, `$.fn.jquery.split` is just `String.prototype.split`. Obviously it doesn't make sense for Cash to implement this, especially considering that Bootstrap seems to be doing some version detection here, which just can't be mapped from jQuery into Cash.

What I'd do in your position is:

1. fork Bootstrap
2. load the fork rather than the original version in your app
3. iteratively patch the fork until it works with cash
4. potentially once everything works maybe you could extract all those patches into a standalone file to be loaded before boostrap is loaded or something
5. once you have a list of all the things that are needed to make Boostrap work with cash I'd be interesting if you could share that list here, perhaps we could implement some of those things in Cash itself
