### ISSUE TITLE
Uncaught TypeError: $.data is not a function

### ISSUE THREAD

**Issue by sdcsystems** [fabiospampinato/cash#351]
I'm trying to get the [jQuery.i18n](https://github.com/wikimedia/jquery.i18n) code to work with Cash.

To stop it complaining about the references to jQuery I have had to add `window.jQuery = cash;` but when I try to load the pages it throws the following error:

```
Uncaught TypeError: $.data is not a function
```

The error message refers to the following line in the jQuery.i18n code:

```
i18n = $.data( document, 'i18n' ),
```

Is there an easy resolution to this or something that I am missing?

-Andy.

**Comment by ornicar** [comment]
This function is not a part of Cash.

You could achieve similar functionality with something like this:

```
document['i18n'] = something;
i18n = document['i18n'];
```

**Comment by fabiospampinato** [comment]
> This function is not a part of Cash.

Exactly. And this won't be part of Cash because the way it works in jQuery is not compatible with stuff like React. 

@sdcsystems you should implement this yourself if you need it. You can find our previous implementation of it by going back enough in git's history, I don't remember exactly when it got removed, that should be mentioned in the changelog.

**Comment by sdcsystems** [comment]
I have no desire to start going back through git commits and start reimplementing functionality.  If there isn't a simple to use i18n library for Cash then I will just dump it and go back to using jQuery.

-Andy.

**Comment by fabiospampinato** [comment]
Not that I know of.
