### ISSUE TITLE
Feedback from porting DataTables

### ISSUE THREAD

**Issue by DataTables** [fabiospampinato/cash#356]
Hi,

Following on from the merge of #347 I've spent some time today experimenting some more with DataTables and Cash. There are a few things that have cropped up, which I thought I'd bring up to see if you would take them as pull requests or not.

Missing utility methods:

* `$.map`
* `$.inArray`
* `$.merge`

There is something different between the return from `$.fn.map` in jQuery and Cash as well, but I've not tracked down what yet. I think it is related to non-DOM elements in the collection.

The final thing I've noticed is that when creating an element, in jQuery you can specify parameters as an object in the second parameter - e.g.:

```
$('<div>', { id: 'whatever' })
```

That can obviously be replaced with:

```
$('<div>').attr('id', 'whatever')l
```

but before I go rewriting my code, is there any desire to see that ability in Cash as well to increase jQuery compatibility? I guess it comes down to how close to jQuery do you want it to be (without it just being jQuery obviously!).

**Comment by fabiospampinato** [comment]
- `$.map`: I think this makes no sense to implement anywhere, [`Array.prototype.map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) is supported from IE9.
- `$.inArray`: There's the relatively new [`Array.prototype.includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) for this, but if you need to support older browsers there's [`Array.prototype.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) which you can use to implement that pretty easily, and that's supported since Chrome v1.
- `$.merge`: This also makes no sense to implement anywhere, you can just use `arr1.push ( ...arr2 )`, or `arr1.push.apply ( arr1, arr2 )` if you don't want to transpile your code.
- `$('<div>', object)`: This maps directly to `$('<div>').attr(object)`, so implementing it doesn't really add much, I think it would be better to have a slightly smaller library instead. But if you can implement that and at the same time squeeze enough bytes out of the library so that the entire thing is no larger than it is now when minified and gzipped then I guess we could add support for this

As a rule of thumb I'd say:

- If you need some major feature that Cash doesn't implement (animation, ajax etc.) that's never going to get implemented, so you'll have to stick with jQuery or find another library for that particular feature
- If you need some minor feature that Cash doesn't implement then probably we are not going to implement that either, unless you really can't do the same thing in a slightly different way with Cash, for example
- If Cash implements something that jQuery implements but our implementation works differently then we should generally align our implementation with jQuery's, but there are some exception to this, mostly mentioned in the [migration guide](https://github.com/fabiospampinato/cash/blob/master/docs/migration_guide.md) (some things in jQuery don't make a lot of sense to me, like some of its methods work with plain objects too for some reason)

**Comment by DataTables** [comment]
Agreed - they can all be implemented quite easily (`$.map` will need a little more work since it needs to cope with both objects and removing `null` values to make it match the jQuery API rather than the ES spec). My reasoning for seeking them to be included in Cash is to increase its utility. I could implement aliases for these methods in DataTables, but it just moves the extra code there, and also to the other libraries that would also look to use Cash as a jQuery replacement.

I certainly don't mind moving things around in DataTables a bit (like the attributes), but writing utility functions when including a utility library feels a little redundant. That said, I love Cash - and I really do want to ship support for it with DataTables (indeed, already made a few changes to remove jQuery specific stuff like a leading `>` in a selector).

**Comment by fabiospampinato** [comment]
I understand your point, at the same time though if jQuery didn't have `$.map` either and you asked for a function like that to be added in Cash I would have said that that's a ridiculous function to add, not just in Cash but anywhere probably, so should we now add it just because jQuery has it? I don't think so, in fact I think jQuery should probably remove it.

Unfortunately that makes writing something that's compatible with both libraries a bit harder, but we've got to draw the line somewhere about what we can and can't add to Cash, and if this line doesn't even exclude something like `$.map` I'm not sure what it should exclude then.

**Comment by DataTables** [comment]
Fair point! To a large extent, a lot of the utility methods that jQuery makes available are largely redundant with the newer changes in ES. At some point I'll need to make the decision of dropping legacy browsers and to what extent and strip out my calls to such methods.

I'll see how small I can make these methods and if it is sensible to then include them into DataTables.
