### ISSUE TITLE
.html method should work exactly like the .html of JQuery

### ISSUE THREAD

**Issue by rmkasendwa** [fabiospampinato/cash#362]
### Feature description

.html method should be as flexible as the .html method of jQuery. It shouldn't just make all it's input a string.

### Feature motivation

There is a discrepancy between the methods. the jquery .html method is able to deal with html elements, collections etc. The cash implementation serializes all input to a string with doesn't work well.

Is this feature present in jQuery? Yes

**Comment by fabiospampinato** [comment]
I'm not following, where did you see $.fn.html doing anything with html collections? If you could provide some code to explain this better it would be useful.

**Comment by rmkasendwa** [comment]
$.fn.html($('<h1>The Header</h1>')) will append an h1 element to the element on which .html is called
Cash.prototype.html($('<h1>The Header</h1>')) will append [Object object] since it attempts stringify the passed object.
I hope this sheds more light

**Comment by fabiospampinato** [comment]
@rmkasendwa Oh interesting, which version of jQuery are you using that with? Because that's not even mentioned in the docs https://api.jquery.com/html/

**Comment by rmkasendwa** [comment]
> @rmkasendwa Oh interesting, which version of jQuery are you using that with? Because that's not even mentioned in the docs https://api.jquery.com/html/

Let me hope this paints the picture https://codepen.io/rmkasendwa/pen/jOVBrJX

**Comment by fabiospampinato** [comment]
Yeah it comes from here: https://github.com/jquery/jquery/blob/025da4dd343e6734f3d3c1b4785b1548498115d8/src/manipulation.js#L400-L402

IMO it doesn't make sense to implement this, mainly because even jQuery doesn't document this behavior, but even if it will be documented I'm not sure it would be worth having this very minor convenience behavior implemented in Cash. Maybe try to have jQuery document this first and then ping me if that happens so that this can be reconsidered.
