### ISSUE TITLE
Search by id selector with escaped chars

### ISSUE THREAD

**Issue by vovayatsyuk** [fabiospampinato/cash#369]
### Current behavior

Selector                        | Cash    | jQuery  
-------------------------------|-----------|----------- 
`$('#id\\.suffix').length`    | 0          | 1
`$('.parent').find('#id\\.suffix').length`    | 1          | 1

### Expected behavior

`$('#id\\.suffix').length` should find the element too.

Codepen: https://codepen.io/vovayatsyuk/pen/WNRzEBM?editors=1010

**Comment by fabiospampinato** [comment]
🤔 The issue seems to be that apparently the selector passed on to `getElementById` is not a selector at all but the actual id of the element to match, so for Cash one should be using "#id.suffix" really, without escaping. 

This should be aligned with jQuery so I'd consider this a bug.

**Comment by cyfung1031** [comment]
@vovayatsyuk 

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

Your id "id.suffix" is not a valid CSS Idenitifier according to W3C recommendation.
You shall change it to "id-suffix" (this is much popular nowadays) or "id_suffix" ( this was popular )

Otherwise, you shall use attribute selector to get the element.

![image](https://user-images.githubusercontent.com/44498510/126290820-40f3666f-fff7-42be-84b7-34420870c382.png)

@fabiospampinato 

`$('.parent').find('#id\\.suffix').length` shall be `0`
The selector `#id.suffix` refers as `<div id="id" class="suffix"></div>`, rather than `<div id="id.suffix"></div>`

**Comment by vovayatsyuk** [comment]
@cyfung1031 I know it's invalid, but sometimes you have to work with incorrect code.

I don't use `#id.suffix` selector. I use `'#id\\.suffix'` instead. These two are different strings and should return different results.
