### ISSUE TITLE
[QUESTION] Select individual methods

### ISSUE THREAD

**Issue by danny007in** [fabiospampinato/cash#372]
For example

```js
import $ from 'cash-dom';
$('html').addClass('dom-loaded')
```

i needed only part of `$` and `addClass`, but not `removeClass` or any other method (Overall i need treeshake example)

**Comment by danny007in** [comment]
@fabiospampinato any solution

**Comment by tvbird** [comment]
+1

**Comment by fabiospampinato** [comment]
Very granular and tiny partial builds can be made, but the documentation about this isn't great.

Overall it's fairly straightforward though, I'd say read [this](https://github.com/fabiospampinato/cash/blob/master/docs/partial_builds.md), then fork the library and edit the "components" section of [`pacco.json`](https://github.com/fabiospampinato/cash/blob/1c1b316e53cc3322e417a93a0e7c4745852796d0/pacco.json#L3-L7) excluding all the paths that you don't need. The way it works is subtractive rather than additive, so you need to tell the compiler which paths to exclude rather than which paths you need. I'd say remove stuff one by one, and if/when stuff breaks the compiler will tell you if you removed something needed by some other file.

If you just need to make literally just a selector function and a `addClass` method it'd be much cleaner to just copy/paste some code out of the library and make your own thing.

These kinds of library based on method chaining can't be tree shaken effectively.
