### ISSUE TITLE
Cannot directly set properties on event argument, resulting in "Uncaught TypeError: Cannot set property data of #<MouseEvent> which has only a getter"

### ISSUE THREAD

**Issue by saurookadook** [fabiospampinato/cash#376]
For use below, here is a branch of a fork of `slick` where the issue can be reproduced: https://github.com/saurookadook/slick/tree/bug/example-for-issue-in-cash

There are HTML files that can be used to replicate the same scenario while using either `cash` or `jQuery`.

### Current behavior
Directly assigning values to `event` argument throws a fatal error of:
```
Uncaught TypeError: Cannot set property data of #<MouseEvent> which has only a getter
```
![cash-error-in-slick](https://user-images.githubusercontent.com/32578064/122225921-7e4dd600-ce83-11eb-93b3-06445f836155.png)

Using the repo above, steps to reproduce are:
- Open the `indexWithCash.html` file in the browser
- Click on any of the "arrow" icons to move to the next set of items in a carousel

### Expected behavior
I would expect this to work similarly to how it does in `jQuery`:
![jquery-success-in-slick](https://user-images.githubusercontent.com/32578064/122225762-58c0cc80-ce83-11eb-8ed0-a61829d0b1de.png)

Using the repo above, steps to reproduce are:
- Open the `indexWithjQuery.html` file in the browser
- Click on any of the "arrow" icons to move to the next set of items in a carousel

#### Workaround
[As I mentioned here](https://github.com/fabiospampinato/cash/issues/364#issuecomment-827870741), it seems like `Object.assign` could be used instead of directly assigning the property.

#### Observations
Based on the types in the above screenshots, it seems like jQuery might be creating CustomEvents that reflect the MouseEvent rather than directly referencing the MouseEvent? That _could_ be a red herring, but I wanted to point that out in case it'd be helpful.

**Comment by fabiospampinato** [comment]
Thanks, I'll look into it when I'll have the time.

Glancing the issue it looks to me like Slick is mutating the event object, which works in jQuery because they have pretty much a custom event system and make their own event objects, but it doesn't work with Cash because we use the browser's event system and event objects, and mutating them is not something that really works across browsers. Cash is doing [this](https://github.com/fabiospampinato/cash/blob/272132a6dc1d885bc25d2874b5740da208698e00/src/events/on.ts#L123-L128) internally just to make that work across browsers.

My guess is that Slick should be updated to make it compatible with Cash, ideally event objects shouldn't be patched at all, but as a quick fix creating new properties like Cash is doing internally might fix the problem.

**Comment by fabiospampinato** [comment]
Closing as it's a problem with third-party libraries we can't do nothing about.
