### ISSUE TITLE
Bootstrap namespaced events do not work

### ISSUE THREAD

**Issue by alecpl** [fabiospampinato/cash#379]
With Bootstrap v5 I do:
```
    import { Modal } from 'bootstrap';
    $('#dialog').on('shown.bs.modal', e => {
        alert('test')
    })
    new Modal('#dialog').show()
```
I see in console that `shown` event is registered on the dialog, but it is not executed.

If I do:
```
    import { Modal } from 'bootstrap';
    $('#dialog')[0].addEventListener('shown.bs.modal', e => {
        alert('test')
    })
    new Modal('#dialog').show()
```
it works.

**Comment by fabiospampinato** [comment]
I guess the way namespaces are handled in Cash is incompatible with Bootstrap.

Does the first snippet work with jQuery? 

For better or for worse in Bootstrap 5 they went with their own thing for DOM manipulation and events, in a why that seems incompatible to how jQuery/Cash do it.

**Comment by philwolstenholme** [comment]
@alecpl Bootstrap 5 dropped jQuery and uses native HTML events which is why `$('#dialog')` didn't work but `$('#dialog')[0]` did work. `$('#dialog')[0]` returns a native HTML element.

If you want to keep using jQuery events, Bootstrap provides an option for that: https://getbootstrap.com/docs/5.0/getting-started/javascript/#events

You'll need to trick Bootstrap into thinking you're using jQuery by doing something like:

```javascript
Object.defineProperty(window, 'jQuery', {
  value: 'fake-jQuery-to-trick-Bootstrap-into-using-jQuery-events-with-Cash',
});
```
