### ISSUE TITLE
What does empty() function do?

### ISSUE THREAD

**Issue by JustACuteGirlLookingForAManToFixHerBugs** [fabiospampinato/cash#381]
I'm a beginner, so 🐻 with me.

> Empties the elements interior markup.

What does it mean?

**Comment by fabiospampinato** [comment]
> Empties the elements interior markup.

That description sounds indeed confusing 🤔 

It just removes all children from the DOM. The code for that is [here](https://github.com/fabiospampinato/cash/blob/272132a6dc1d885bc25d2874b5740da208698e00/src/manipulation/empty.ts#L13-L17).

In general if you are learning about this stuff I'd recommend getting the documentation from jQuery instead, which is much more in depth and works basically the same: https://api.jquery.com/ It might be a good idea to use jQuery the library itself too instead of Cash for now, and then perhaps switch to Cash as an optimization.
