### ISSUE TITLE
Cash conflict with jQuery

### ISSUE THREAD

**Issue by boychanhboy** [fabiospampinato/cash#394]
I'm currently using cash.js instead of jQuery, but i got an issue. In product detail, i must use 3rd app to show/write product reviews. This app use jQuery 3.4.1 and Fancybox, console log has an error: "Uncaught TypeError: invalid 'instanceof' operand jQuery"
Ex: `https://mew-yummy.mysapo.net/ot-ngot-da-lat`

How can i handle this error, i can't change any thing in reviews app, how can i change $ of cash.js to another symbol instead to prevent this?

Best regards,

**Comment by fabiospampinato** [comment]
I'm not sure what the problem is exactly or how to solve it.

From what I can see there's no "jQuery" global in that page, so it looks like jQuery isn't being loaded at all?

If you want to assign cash to another variable you just do something like this after loading cash: `window.cash = window.$`, then you can use it from the "cash" global for example.

**Comment by boychanhboy** [comment]
Thank you for reply,
Review apps only need jQuery in product detail page, I'll try your solution and update later
Best regards.
